/**
 * The edit decision list. One entry per picture segment, in order. Steve drops
 * recordings into video/assets/ and tunes `startFrom`/`duration` here; the
 * Final composition renders the whole film from this table plus the voice (see VO below).
 *
 * Workflow: picture is locked first (out/gallery-402-silent.mp4), the VO is read
 * to it, then trims here are nudged to the voice. `duration` is seconds on
 * screen; `startFrom` is seconds into the source recording to begin at.
 */
/** A camera keyframe: at `at` seconds into the segment the picture is scaled
 *  `scale`× about the point (`x`%, `y`%). Moves between keyframes are eased;
 *  the frame holds before the first and after the last. */
export type Cam = { at: number; scale: number; x: number; y: number }

export type Segment =
  | { kind: 'card'; comp: 'Title' | 'X402Flow' | 'EndCard'; duration: number }
  | { kind: 'clip'; src: string; startFrom: number; duration: number; label: string; rate?: number; dipIn?: boolean; dipOut?: boolean; caption?: string; captionHold?: number; cam?: Cam[] }
  | { kind: 'still'; src: string; duration: number; label: string }

/** Voice: 'cues' plays the per-beat clips generated by `vo/generate.mjs`
 *  (assets/vo/<id>.mp3, placed at each cue's `at`); a filename plays one
 *  continuous take from assets/; null renders silent. */
export const VO: 'cues' | string | null = 'cues'

export const EDL: Segment[] = [
  // 0:00 cold open — the clean re-take (take2: sidebar collapsed, fresh chat,
  // museum staged at gallery402.stacktr.ee before rolling)
  { kind: 'clip', src: 'r1-take2.mp4', startFrom: 2, duration: 10, label: 'cold open: the ask typed', dipOut: false, caption: 'ChatGPT Work · the museum is the tab beside it' },
  // the 84 thinking seconds, fast-forwarded — the skip becomes the agent working
  { kind: 'clip', src: 'r1-take2.mp4', startFrom: 12, duration: 3, rate: 28, label: 'cold open: agent working (28×)', dipIn: false, dipOut: false, caption: '28× — the agent composing a tour no curator wrote' },
  { kind: 'clip', src: 'r1-take2.mp4', startFrom: 96, duration: 23, label: 'cold open: ask → yes → purchase → Water Lilies', dipIn: false, caption: 'it asks before spending — then pays over HTTP 402' },
  { kind: 'card', comp: 'Title', duration: 8 },
  { kind: 'card', comp: 'X402Flow', duration: 19 }, // through the closing line ('No account. No card form. No redirect.')
  // 0:52 proof it's real — R2: drip, buy, ledger settles…
  { kind: 'clip', src: 'r2-chrome.mp4', startFrom: 5, duration: 9, label: 'human path: pay', caption: 'no agent needed: one click, a real 402, settled on-chain' },
  // …the transaction itself (basescan refuses headless filming; a still works)
  { kind: 'still', src: 'basescan.jpg', duration: 5, label: 'the settlement' },
  // …then walk in to the Great Wave at true size
  { kind: 'clip', src: 'r2-chrome.mp4', startFrom: 14, duration: 9, label: 'human path: enter', caption: 'full resolution only with a ticket — hung at true size' },
  // 1:22 back to the agent — R1 continued: tour runs, docent notes, save_tour
  { kind: 'clip', src: 'r1-take2.mp4', startFrom: 126, duration: 8, label: 'agent path: docent note hold', dipOut: false, caption: 'wall notes written for a daughter who loves boats' },
  { kind: 'clip', src: 'r1-take2.mp4', startFrom: 134, duration: 1.3, rate: 12.3, label: 'fast-forward to the walk', dipIn: false, dipOut: false },
  { kind: 'clip', src: 'r1-take2.mp4', startFrom: 150, duration: 18, label: 'agent path: the walk (Lilies → Cliff Walk → Sunrise)', dipIn: false, dipOut: false },
  { kind: 'clip', src: 'r1-take2.mp4', startFrom: 168, duration: 1.5, rate: 21.3, label: 'fast-forward to the publish', dipIn: false, dipOut: false },
  { kind: 'clip', src: 'r1-take2.mp4', startFrom: 200, duration: 8, label: 'agent path: published', dipIn: false },
  // the payoff: the page the visit became — works, the agent's notes, receipts
  { kind: 'clip', src: 'keepsake.mp4', startFrom: 2.5, duration: 12, label: 'the keepsake, scrolled', caption: 'the page the visit became — notes and receipts included', captionHold: 7.5 }, // chip clears the frame before the receipt scrolls in
  // 2:15 the living surface — R3. The panel text is small at 1080p, so the
  // camera pushes 1.5× onto the box office as the Buy lands (5.7s), holds
  // through enter_wing appearing (7.2s), then tilts up to the tool panel and
  // the header pill for the tick to 14 (9.2s).
  { kind: 'clip', src: 'r3-surface.mp4', startFrom: 3.3, duration: 13.5, label: 'surface', caption: 'the tool list is alive — buying reshapes what agents can do',
    cam: [
      { at: 4.6, scale: 1, x: 100, y: 100 },
      { at: 5.6, scale: 1.5, x: 100, y: 100 },
      { at: 8.2, scale: 1.5, x: 100, y: 100 },
      { at: 9.2, scale: 1.5, x: 100, y: 0 },
    ] },
  { kind: 'card', comp: 'EndCard', duration: 20 }, // long hold: the close VO runs ~18.6s, then the URLs sit in silence
]
